### ISSUE TITLE
Symlinks seems stopped after update node.

### ISSUE THREAD

**Issue by lazaronixon** [aleclarson/get-dev-paths#1]
```js
const fs = require('fs')
const getDevPaths = require('get-dev-paths')

const projectRoot = __dirname
module.exports = {
  // Old way
  getProjectRoots: () => Array.from(new Set(
    getDevPaths(projectRoot).map($ => fs.realpathSync($))
  )),
  // New way
  watchFolders: Array.from(new Set(
    getDevPaths(projectRoot).map($ => fs.realpathSync($))
  ))
}
```

<img width="483" alt="image" src="https://user-images.githubusercontent.com/2651240/49391208-2a8a9f80-f712-11e8-8cb1-1aac06ea60c5.png">

node: 11.3.0
metro: 0.50.0

**Comment by aleclarson** [comment]
What does your `node_modules` and `package.json` look like?

**Comment by lazaronixon** [comment]
package.json
```
{
  "name": "Example",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "get-dev-paths": "^0.1.0",
    "react": "16.6.1",
    "react-native": "0.57.7",
    "react-native-turbolinks": "file:../",
    "react-native-webview": "^2.8.1"
  },
  "devDependencies": {
    "metro-react-native-babel-preset": "0.50.0"
  }
}
```
<img src="https://user-images.githubusercontent.com/2651240/49393724-375ec180-f719-11e8-90f1-023ebaf7baf6.png" width="150">
<img src="https://user-images.githubusercontent.com/2651240/49393763-52c9cc80-f719-11e8-89f2-e59c325620eb.png" width="150">

**Comment by aleclarson** [comment]
1. Do you get this error without `getDevPaths`?
2. Is `node_modules/@babel/runtime` a symlink?

Try locking your `metro` version to `v0.47.0`. Or provide a minimal repro (as a Github repo) and I can look into this myself.

**Comment by lazaronixon** [comment]
1. No.. If remove getDevPaths I see error on react-native-turbolinks module only.
2. No, Its is not a symlink

You can try my repo: https://github.com/lazaronixon/react-native-turbolinks/tree/v2.0.4

**Comment by aleclarson** [comment]
Pinning your `metro` version is **highly** advised, because React Native doesn't bump their major version when bumping their `metro` dependency. This means your `metro.config.js` can break when upgrading the minor/patch version of React Native.

**Comment by aleclarson** [comment]
It's possible that [this `metro` commit](https://github.com/facebook/metro/commit/039dedb4aaf5c0002c8e2f82279fbb5a6849ea69) is the culprit. It's a major version bump to `jest-haste-map` (which is mentioned in your error message) inside a patch version of `metro` (v0.48.2 to be exact). [In this `react-native` commit,](https://github.com/facebook/react-native/commit/f867db366aa4f0ead5a20c0d3154ca58be43fc20#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) you can see someone complained about that same version breaking React Native's CI.

**Comment by aleclarson** [comment]
The fact that `@babel/runtime` is not a symlink makes me certain this is not the fault of `get-dev-paths`. But please let me know if pinning `metro` to v0.48.1 fixes the problem.

**Comment by lazaronixon** [comment]
=/ Same problem with 0.48.1, 0.47.0, 0.46.0

**Comment by lazaronixon** [comment]
I found the problem.. At end it was add "@babel/runtime" to dev depency of library not example project. Thanks for your time.
