### ISSUE TITLE
not working, unless add the dependency which you linked in your package.json manually

### ISSUE THREAD

**Issue by luogao** [aleclarson/get-dev-paths#3]
I am working on a React-Native project, and I need test a package locally, before I publish it. So I need  use `yarn link`

But `yarn link` does not work well with React-Native, because motro bundler does not support `yarn link` or  `npm link`.

But I found [`metro-symlinked-deps`](https://github.com/Carimus/metro-symlinked-deps), which will work according to its introduction.

So I tried it, but it not work well.

Then I check the [`metro-symlinked-deps`](https://github.com/Carimus/metro-symlinked-deps) source code, I found out it used this lib to get the linking package's path.

After some dig out, I found the local linking package path will not output unless it's name is in the project package.json

```javascript 
          fs.readdirSync(path.join(depsDir, name)).forEach(function(name) {
            if (deps[name = scope + '/' + name]) {
              return addPath(path.join(depsDir, name));
            }
          });

```
 
But seems like `yarn link` or `npm link` won't add the linking package name in the `package.json`

Currently, I add my local package's name in `package.json` manually. Like this:

``` json
"dependencies": {
    "myPackageName" : "*"
},

```

And it worked ~

I'm not sure whether I'm doing right or not, and the doc does not mention this.

So, could you help me to solve this problem? 

Thanks a lot!

**Comment by aleclarson** [comment]
Yeah, the dependency must exist in `package.json`. I've clarified this in the readme.
